hk_ex_news_fetcher:
  every:
    - "300s"
    - :first_in: '30s'
  class: "HkExNewsFetcher"
  queue: hk_ex_news_fetcher
  description: "Fetch hkexnews.hk main board news of today into database every 300 seconds."

hk_ex_news_fetcher_growth:
  every:
    - "300s"
    - :first_in: '90s'
  class: "HkExNewsFetcher"
  queue: hk_ex_news_fetcher
  args: "growth"
  description: "Fetch hkexnews.hk growth enterprise market news of today into database every 300 seconds."

hk_ex_news_fetcher_warrant:
  every:
    - "600s"
    - :first_in: '180s'
  class: "HkExNewsFetcher"
  queue: hk_ex_news_fetcher
  args: "warrant"
  description: "Fetch hkexnews.hk derivative warrants news of today into database every 600 seconds."

hk_ex_news_fetcher_others:
  every:
    - "600s"
    - :first_in: '300s'
  class: "HkExNewsFetcher"
  queue: hk_ex_news_fetcher
  args: "others"
  description: "Fetch hkexnews.hk others (CBBC, Funds, etc.) news of the week into database every 600 seconds."
