# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc576f1a60a8b564442f3a5311fd54aa7cce35adc070dc819b8d3487257e39fad8a04723f05a139a7013d00cd07d7dd5971f82e35cc5c283530c70154f70596b
  devise_secret_key: 1229f05d11d8d4c30092bdd8ebab00b50cef34034ccf771ca076f6330d2b8281ba9232ddc7ec9fbe2695f9719f8034e2c9c0cd61b93f51df19eb960926206e49
  mandrill_username: <%= ENV['MANDRILL_USERNAME'] %>
  mandrill_apikey: <%= ENV['MANDRILL_APIKEY'] %>
  bitly_access_token: <%= ENV['BITLY_ACCESS_TOKEN'] %>
  rediscloud_url: <%= ENV["REDISCLOUD_URL"] %>
  new_relic_license_key: <%= ENV["NEW_RELIC_LICENSE_KEY"] %>
  new_relic_app_name: <%= ENV["NEW_RELIC_APP_NAME"] %>

test:
  secret_key_base: 34f838755bd3e91ce851671b3f126d0b44a7d5e1e55f6923a85500c689798c875689cc3e1e6c9bc53e8cf407e22ad77535c66cdd081cc8090afff7d9123fb192
  devise_secret_key: 7c59f4bca493fcfeb540a47f1b35bb0c691ba0182e6a874ac678c23f6594b45a9a98a50d2d93b96f4384110606e89a3617afe52f35d04bae9296bd0aeb8290d5
  mandrill_username: <%= ENV['MANDRILL_USERNAME'] %>
  mandrill_apikey: <%= ENV['MANDRILL_APIKEY'] %>
  bitly_access_token: <%= ENV['BITLY_ACCESS_TOKEN'] %>
  rediscloud_url: <%= ENV["REDISCLOUD_URL"] %>
  new_relic_license_key: <%= ENV["NEW_RELIC_LICENSE_KEY"] %>
  new_relic_app_name: <%= ENV["NEW_RELIC_APP_NAME"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
  mandrill_username: <%= ENV['MANDRILL_USERNAME'] %>
  mandrill_apikey: <%= ENV['MANDRILL_APIKEY'] %>
  bitly_access_token: <%= ENV['BITLY_ACCESS_TOKEN'] %>
  rediscloud_url: <%= ENV["REDISCLOUD_URL"] %>
  new_relic_license_key: <%= ENV["NEW_RELIC_LICENSE_KEY"] %>
  new_relic_app_name: <%= ENV["NEW_RELIC_APP_NAME"] %>
